# Generated by Django 5.1.1 on 2024-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0002_task_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
    ]
