# Generated by Django 5.1.1 on 2024-09-05 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0003_task_due_date_task_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 10, 46, 49, 938693)),
        ),
    ]
